pipeline {
    agent any
    tools {
        maven 'maven-3.6.3'
    }
    stages{
        stage('Build') {
            steps {
                sh 'mvn clean'
            }
        }
        stage('Test'){
            steps {
                echo 'Testing...'
            }
        }
        stage('Deliver') {
            steps {
                echo 'Delivering...'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying...'
            }
        }
    }
}